### ISSUE TITLE
add support to re-start CI checks if they failed

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/test-harness#14]
Recently CI failed due to low disk space on the test runner. There should be an option to re-trigger CI checks after this was fixed.

**Comment by pcahyna** [comment]
> There should be an option to re-trigger CI checks

Indeed. I spent some time investigating this already. The easiest would seem to delete the status, unfortunately the GitHub API does not support deleting statuses, only adding them. Another idea would be to let the test harness retry tests when they have the status of "error" instead of "failure". One can then change the status to "error" manually to re-trigger them.

**Comment by pcahyna** [comment]
Only via the REST API.

**Comment by tyll** [comment]
This is now possible with using special comments such as [citest bad]
